#pragma once

// From glfw3.h
#define NEON_MOUSE_BUTTON_1         0
#define NEON_MOUSE_BUTTON_2         1
#define NEON_MOUSE_BUTTON_3         2
#define NEON_MOUSE_BUTTON_4         3
#define NEON_MOUSE_BUTTON_5         4
#define NEON_MOUSE_BUTTON_6         5
#define NEON_MOUSE_BUTTON_7         6
#define NEON_MOUSE_BUTTON_8         7
#define NEON_MOUSE_BUTTON_LAST      NEON_MOUSE_BUTTON_8
#define NEON_MOUSE_BUTTON_LEFT      NEON_MOUSE_BUTTON_1
#define NEON_MOUSE_BUTTON_RIGHT     NEON_MOUSE_BUTTON_2
#define NEON_MOUSE_BUTTON_MIDDLE    NEON_MOUSE_BUTTON_3